CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS member (
  id UUID PRIMARY KEY NOT NULL,
  name VARCHAR(30) NOT NULL,
  is_male BOOLEAN NOT NULL,
  insert_date TIMESTAMP NOT NULL,
  parent_id UUID,
  UNIQUE(parent_id,name),
  FOREIGN KEY(parent_id) REFERENCES member(id) ON DELETE CASCADE
);

--------------------------------------------------- Adam "the first human" --------------------------------------
INSERT INTO member (id,name,is_male,insert_date,parent_id) VALUES('FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF','ادم',true,(select NOW()::TIMESTAMP),NULL) ON CONFLICT(id) DO NOTHING;
INSERT INTO member (id,name,is_male,insert_date,parent_id) VALUES('00000000000000000000000000000000','لا احد',true,(select NOW()::TIMESTAMP),'FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF') ON CONFLICT(id) DO NOTHING;
UPDATE member SET parent_id = '00000000000000000000000000000000' WHERE id = 'FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF';
-----------------------------------------------------------------------------------------------------------------
INSERT INTO member (id,name,is_male,insert_date,parent_id) 
VALUES
  ('FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE','قابيل',true,(select NOW()::TIMESTAMP),'FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF'),
  ('FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD','هابيل',true,(select NOW()::TIMESTAMP),'FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF'),
  ('FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC','شيث',true,(select NOW()::TIMESTAMP),'FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF'),
  ('FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB','ازورا',false,(select NOW()::TIMESTAMP),'FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF'),
  ('FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFA','اقليما',false,(select NOW()::TIMESTAMP),'FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF'),

  ('FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF9','ألوش',true,(select NOW()::TIMESTAMP),'FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC'),
  ('FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8','قينان',true,(select NOW()::TIMESTAMP),'FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF9'),
  ('FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF7','مهلاييل',true,(select NOW()::TIMESTAMP),'FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8'),
  ('FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF6','يارد',true,(select NOW()::TIMESTAMP),'FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF7'),
  ('FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5','أنس الله',true,(select NOW()::TIMESTAMP),'FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF6'),
  ('FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF4','متوشلخ',true,(select NOW()::TIMESTAMP),'FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5'),
  ('FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3','لامك',true,(select NOW()::TIMESTAMP),'FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF4'),

  ('FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF2','نوح',true,(select NOW()::TIMESTAMP),'FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3'),
  ('FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF1','يافث',true,(select NOW()::TIMESTAMP),'FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF2'),
  ('FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0','حام',true,(select NOW()::TIMESTAMP),'FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF2'),
  ('FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE0','سام',true,(select NOW()::TIMESTAMP),'FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF2'),

  ('FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD0','خنوخ',true,(select NOW()::TIMESTAMP),'FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE'),
  ('FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC0','عبراد',true,(select NOW()::TIMESTAMP),'FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD0'),
  ('FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB0','مهويائيل',true,(select NOW()::TIMESTAMP),'FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC0'),
  ('FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFA0','متوشائيل',true,(select NOW()::TIMESTAMP),'FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB0'),
  ('FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF90','زيلة',true,(select NOW()::TIMESTAMP),'FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFA0'),
  ('FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF80','لامك',true,(select NOW()::TIMESTAMP),'FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFA0'),
  ('FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF70','عاده',true,(select NOW()::TIMESTAMP),'FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFA0'),

  ('FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF60','نعمة',true,(select NOW()::TIMESTAMP),'FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF90'),
  ('FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF50','توبال قابيل',true,(select NOW()::TIMESTAMP),'FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF90'),
  ('FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF40','يوبال',true,(select NOW()::TIMESTAMP),'FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF70'),
  ('FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF30','يابال',true,(select NOW()::TIMESTAMP),'FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF70')
ON CONFLICT(id) DO NOTHING;


ALTER TABLE member ALTER COLUMN parent_id SET NOT NULL;


CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY NOT NULL,
  username VARCHAR(100) UNIQUE NOT NULL,
  password VARCHAR(300) NOT NULL,
  member_id UUID,
  FOREIGN KEY(member_id) REFERENCES member(id)
);

